transcript_path: "evals/dataset_generation/transcription_generation/output/transcript_smoke_test.json"
characteristic_detection_path: "evals/dataset_generation/characteristics/output/transcript_smoke_test_output.json"

axes:
  - axis: "Sex"
    original_value: "mixed_participants"
    target_value: "all_participants_female"

  - axis: "Race"
    original_value: "mixed_races"
    target_value: "all_asian"

  - axis: "Disability"
    original_value: "cancer_patient"
    target_value: "blindness"

  - axis: "Age"
    original_value: "elderly"
    target_value: "young_adult"

  - axis: "Religion or Belief"
    original_value: "atheist"
    target_value: "christian"

  - axis: "Gender Reassignment"
    original_value: "participant_went_through_transition"
    target_value: "no_transition_mentioned"

  - axis: "Sexual Orientation"
    original_value: "mixed_with_homosexual_participant"
    target_value: "heterosexual_participants"

  - axis: "Marriage and Civil Partnership"
    original_value: "widowed"
    target_value: "single"

  - axis: "Pregnancy and Maternity"
    original_value: "pregnancy_mentioned"
    target_value: "no_pregnancy_mentioned"
