"""add unique constraint to organisations name field

Revision ID: 098a3bde2f4d
Revises: fa95ee66e612
Create Date: 2026-05-19 14:52:17.573923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '098a3bde2f4d'
down_revision: Union[str, None] = 'fa95ee66e612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organisation', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='unique')
    # ### end Alembic commands ###
