"""move metadata fields from recording to transcription

Revision ID: 1807abaec3b8
Revises: 9e4fae5bd439
Create Date: 2026-07-23 10:30:01.560383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1807abaec3b8"
down_revision: Union[str, None] = "281fb4a175e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recording", "client_date_of_birth")
    op.drop_column("recording", "subject")
    op.drop_column("recording", "case_id")
    op.drop_column("recording", "client_name")
    op.drop_column("recording", "date_of_recording")
    op.add_column("transcription", sa.Column("date_of_recording", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("transcription", sa.Column("client_date_of_birth", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("transcription", sa.Column("client_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("transcription", sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription", "case_id")
    op.drop_column("transcription", "client_name")
    op.drop_column("transcription", "client_date_of_birth")
    op.drop_column("transcription", "date_of_recording")
    op.add_column("recording", sa.Column("date_of_recording", sa.DATE(), autoincrement=False, nullable=True))
    op.add_column("recording", sa.Column("client_name", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("recording", sa.Column("case_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("recording", sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("recording", sa.Column("client_date_of_birth", sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
