"""add tou to user

Revision ID: 281fb4a175e1
Revises: 9e4fae5bd439
Create Date: 2026-07-17 12:18:27.049448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "281fb4a175e1"
down_revision: Union[str, None] = "9e4fae5bd439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("accepted_tou", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "accepted_tou")
    # ### end Alembic commands ###
