"""add organisation id to user

Revision ID: 34b20dff2f0a
Revises: a0af26106af7
Create Date: 2026-05-06 16:14:37.517670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "34b20dff2f0a"
down_revision: Union[str, None] = "a0af26106af7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("organisation_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_user_organisation_id", "user", "organisation", ["organisation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_organisation_id", "user", type_="foreignkey")
    op.drop_column("user", "organisation_id")
    # ### end Alembic commands ###
