"""add subject id to user

Revision ID: 4c50cdc7bc19
Revises: 68a4b2dd8839
Create Date: 2026-05-29 14:33:51.097183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c50cdc7bc19'
down_revision: Union[str, None] = '68a4b2dd8839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT_NAME = "uq_user_subject_id"

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(CONSTRAINT_NAME, 'user', ['subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(CONSTRAINT_NAME, 'user', type_='unique')
    op.drop_column('user', 'subject_id')
    # ### end Alembic commands ###
