"""add unique constraint to user email

Revision ID: 5c1e1d353f2a
Revises: aeda129e5d02
Create Date: 2026-06-17 16:23:53.747727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5c1e1d353f2a"
down_revision: Union[str, None] = "aeda129e5d02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")

    # manual edit
    # remove duplicate emails before enforcing uniqueness, keeping the oldest row per email
    op.execute("""
        DELETE FROM "user" a
        USING "user" b
        WHERE a.email = b.email
          AND a.id > b.id
    """)
    # end manual edit

    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


# Note: rows deleted during upgrade() (duplicate emails) are not restored here.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###
