"""drop nullable retention period option

Revision ID: 5d713f0c5d22
Revises: d7f3a9c21e84
Create Date: 2026-07-13 17:11:36.876339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = "5d713f0c5d22"
down_revision: Union[str, None] = "d7f3a9c21e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual edit to set a default value for existing records before making the column non-nullable

    user_table = table("user", column("data_retention_days"))

    op.execute(user_table.update().where(user_table.c.data_retention_days.is_(None)).values(data_retention_days=30))

    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("user", "data_retention_days", existing_type=sa.INTEGER(), nullable=False)


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("user", "data_retention_days", existing_type=sa.INTEGER(), nullable=True)


# ### end Alembic commands ###
