"""add analytics event table and recording source

Revision ID: 7c1d4a9b2e83
Revises: 4bdf73c04aea
Create Date: 2026-09-24 17:40:12.114927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c1d4a9b2e83"
down_revision: Union[str, None] = "4bdf73c04aea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    analyticseventname = postgresql.ENUM(
        "LIVE_RECORDING_STARTED_OR_UPLOAD_REQUESTED",
        "AUDIO_UPLOAD_COMPLETE_FROM_LIVE_RECORDING",
        "AUDIO_UPLOAD_COMPLETE_FROM_DIRECT_UPLOAD",
        "TRANSCRIPT_REQUESTED_FOR_LIVE_RECORDING",
        "TRANSCRIPT_REQUESTED_FOR_DIRECT_UPLOAD",
        "TRANSCRIPT_RECEIVED_FOR_LIVE_RECORDING",
        "TRANSCRIPT_RECEIVED_FOR_DIRECT_UPLOAD",
        "SUMMARY_REQUESTED",
        "SUMMARY_RECEIVED",
        name="analyticseventname",
        create_type=False,  # created explicitly below, so the table create must not create it again
    )
    analyticseventname.create(op.get_bind(), checkfirst=True)  # manual edit to create enum

    recordingsource = postgresql.ENUM(
        "LIVE_RECORDING", "DIRECT_UPLOAD", name="recordingsource", create_type=False
    )
    recordingsource.create(op.get_bind(), checkfirst=True)  # manual edit to create enum

    op.create_table(
        "analytics_event",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_datetime", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("name", analyticseventname, nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analytics_event_name"), "analytics_event", ["name"], unique=False)
    op.add_column("recording", sa.Column("source", recordingsource, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recording", "source")
    op.drop_index(op.f("ix_analytics_event_name"), table_name="analytics_event")
    op.drop_table("analytics_event")
    sa.Enum(name="recordingsource").drop(op.get_bind(), checkfirst=True)  # manual edit to delete enum
    sa.Enum(name="analyticseventname").drop(op.get_bind(), checkfirst=True)  # manual edit to delete enum
    # ### end Alembic commands ###
