"""drop_nullable_data_retention_option

Revision ID: 9e4fae5bd439
Revises: 9190327339e4
Create Date: 2026-07-14 10:05:06.256707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '9e4fae5bd439'
down_revision: Union[str, None] = '9190327339e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

# Manual edit to set a default value for existing records before making the column non-nullable

  

    user_table = table("user", column("data_retention_days"))

    op.execute(user_table.update().where(user_table.c.data_retention_days.is_(None)).values(data_retention_days=30))


# ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("user", "data_retention_days", existing_type=sa.INTEGER(), nullable=False)

  
  

# ### end Alembic commands ###

def downgrade() -> None:

# ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("user", "data_retention_days", existing_type=sa.INTEGER(), nullable=True)
  
# ### end Alembic commands ###