"""add subject id to user

Revision ID: a664ef400782
Revises: 68a4b2dd8839
Create Date: 2026-05-28 11:34:05.003963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a664ef400782"
down_revision: Union[str, None] = "68a4b2dd8839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("subject_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "subject_id")
    # ### end Alembic commands ###
