"""add last login to user

Revision ID: aeda129e5d02
Revises: 4c50cdc7bc19
Create Date: 2026-06-15 13:32:48.013767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "aeda129e5d02"
down_revision: Union[str, None] = "4c50cdc7bc19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_login", sa.TIMESTAMP(timezone=True), nullable=True))

    # manual edit
    # backfill existing users then make column nullable again (syncing back to model)
    op.execute('UPDATE "user" SET last_login = NOW() WHERE last_login IS NULL')
    op.alter_column("user", "last_login", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login")
    # ### end Alembic commands ###
