"""add user roles

Revision ID: bf3e4dac2dcd
Revises: 9d080ca9fe6c
Create Date: 2026-05-05 13:27:45.518578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf3e4dac2dcd"
down_revision: Union[str, None] = "9d080ca9fe6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum(
        "STANDARD_USER",
        "LOCAL_AUTHORITY_ADMIN",
        "MHCLG_SUPPORT_ADMIN",
        name="userrole",
    )
    userrole.create(op.get_bind(), checkfirst=True)  # manual edit to create enum
    op.add_column(
        "user",
        sa.Column(
            "roles",
            postgresql.ARRAY(userrole),
            server_default=sa.text("ARRAY['STANDARD_USER']::userrole[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "roles")
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)  # manual edit to delete enum
    # ### end Alembic commands ###
