"""empty message

Revision ID: e06b488cb0ff
Revises: d7f3a9c21e84
Create Date: 2026-07-13 16:09:42.075570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e06b488cb0ff'
down_revision: Union[str, None] = 'd7f3a9c21e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'data_retention_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'data_retention_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
