"""use citext for user emails

Revision ID: f4510d2ab4af
Revises: 5c1e1d353f2a
Create Date: 2026-06-24 15:33:36.108084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4510d2ab4af"
down_revision: Union[str, None] = "5c1e1d353f2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # manual edit - introduce CITEXT type
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    op.alter_column("user", "email", existing_type=sa.VARCHAR(), type_=postgresql.CITEXT(), existing_nullable=False)
    op.drop_index(op.f("ix_user_email_lower"), table_name="user")
    op.create_unique_constraint("uq_user_email", "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_email", "user", type_="unique")
    op.create_index(op.f("ix_user_email_lower"), "user", [sa.literal_column("lower(email::text)")], unique=True)
    op.alter_column("user", "email", existing_type=postgresql.CITEXT(), type_=sa.VARCHAR(), existing_nullable=False)

    # manual edit - drop CITEXT type
    op.execute("DROP EXTENSION IF EXISTS citext")
    # ### end Alembic commands ###
