"""add organisation id to user

Revision ID: fa95ee66e612
Revises: 59db8aa6464c
Create Date: 2026-05-13 10:47:15.114725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fa95ee66e612"
down_revision: Union[str, None] = "59db8aa6464c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FOREIGN_KEY = "fk_user_organisation_id"  # manually define foreign key name


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("organisation_id", sa.UUID(), nullable=True))
    op.create_foreign_key(FOREIGN_KEY, "user", "organisation", ["organisation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FOREIGN_KEY, "user", type_="foreignkey")
    op.drop_column("user", "organisation_id")
    # ### end Alembic commands ###
