run:
  eval_type: standard
  output_dir: evals/summarisation/output
  prompt_version: dev
  dataset_version: unspecified
  limit: 2

dataset:
  name: knkarthick/dialogsum
  config: default
  dialogue_field: dialogue
  reference_summary_field: summary

judge:
  pass_threshold: 4

prompts:
  summarizer_template_name: General
  judge_template_path: evals/summarisation/prompts/judge.j2

hallucination:
  enabled: true
