// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CreateChatTranscriptionsTranscriptionIdChatPostData,
  CreateChatTranscriptionsTranscriptionIdChatPostErrors,
  CreateChatTranscriptionsTranscriptionIdChatPostResponses,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostResponses,
  CreateMinuteVersionMinutesMinuteIdVersionsPostData,
  CreateMinuteVersionMinutesMinuteIdVersionsPostErrors,
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponses,
  CreateOrganisationOrganisationsPostData,
  CreateOrganisationOrganisationsPostErrors,
  CreateOrganisationOrganisationsPostResponses,
  CreateRecordingRecordingsPostData,
  CreateRecordingRecordingsPostErrors,
  CreateRecordingRecordingsPostResponses,
  CreateTranscriptionTranscriptionsPostData,
  CreateTranscriptionTranscriptionsPostErrors,
  CreateTranscriptionTranscriptionsPostResponses,
  CreateUserTemplateUserTemplatesPostData,
  CreateUserTemplateUserTemplatesPostErrors,
  CreateUserTemplateUserTemplatesPostResponses,
  CreateUserUsersPostData,
  CreateUserUsersPostErrors,
  CreateUserUsersPostResponses,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteResponses,
  DeleteOrganisationOrganisationsOrganisationIdDeleteData,
  DeleteOrganisationOrganisationsOrganisationIdDeleteErrors,
  DeleteOrganisationOrganisationsOrganisationIdDeleteResponses,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteResponses,
  DeleteUserUsersUserIdDeleteData,
  DeleteUserUsersUserIdDeleteErrors,
  DeleteUserUsersUserIdDeleteResponses,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponses,
  EditUserTemplateUserTemplatesTemplateIdPatchData,
  EditUserTemplateUserTemplatesTemplateIdPatchErrors,
  EditUserTemplateUserTemplatesTemplateIdPatchResponses,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses,
  GetMinuteMinutesMinutesIdGetData,
  GetMinuteMinutesMinutesIdGetErrors,
  GetMinuteMinutesMinutesIdGetResponses,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses,
  GetOrganisationOrganisationsOrganisationIdGetData,
  GetOrganisationOrganisationsOrganisationIdGetErrors,
  GetOrganisationOrganisationsOrganisationIdGetResponses,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses,
  GetTargetUserUsersUserIdGetData,
  GetTargetUserUsersUserIdGetErrors,
  GetTargetUserUsersUserIdGetResponses,
  GetTemplatesTemplatesGetData,
  GetTemplatesTemplatesGetErrors,
  GetTemplatesTemplatesGetResponses,
  GetTranscriptionTranscriptionsTranscriptionIdGetData,
  GetTranscriptionTranscriptionsTranscriptionIdGetErrors,
  GetTranscriptionTranscriptionsTranscriptionIdGetResponses,
  GetUserTemplatesUserTemplatesGetData,
  GetUserTemplatesUserTemplatesGetErrors,
  GetUserTemplatesUserTemplatesGetResponses,
  GetUserTemplateUserTemplatesTemplateIdGetData,
  GetUserTemplateUserTemplatesTemplateIdGetErrors,
  GetUserTemplateUserTemplatesTemplateIdGetResponses,
  GetUserUsersMeGetData,
  GetUserUsersMeGetErrors,
  GetUserUsersMeGetResponses,
  HealthcheckHealthcheckGetData,
  HealthcheckHealthcheckGetResponses,
  ListChatTranscriptionsTranscriptionIdChatGetData,
  ListChatTranscriptionsTranscriptionIdChatGetErrors,
  ListChatTranscriptionsTranscriptionIdChatGetResponses,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses,
  ListMinuteVersionsMinutesMinuteIdVersionsGetData,
  ListMinuteVersionsMinutesMinuteIdVersionsGetErrors,
  ListMinuteVersionsMinutesMinuteIdVersionsGetResponses,
  ListOrganisationsOrganisationsGetData,
  ListOrganisationsOrganisationsGetErrors,
  ListOrganisationsOrganisationsGetResponses,
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData,
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetErrors,
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponses,
  ListTranscriptionsTranscriptionsGetData,
  ListTranscriptionsTranscriptionsGetErrors,
  ListTranscriptionsTranscriptionsGetResponses,
  ListUsersUsersGetData,
  ListUsersUsersGetErrors,
  ListUsersUsersGetResponses,
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData,
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchErrors,
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponses,
  SignOutSignoutGetData,
  SignOutSignoutGetResponses,
  UpdateDataRetentionUsersDataRetentionPatchData,
  UpdateDataRetentionUsersDataRetentionPatchErrors,
  UpdateDataRetentionUsersDataRetentionPatchResponses,
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData,
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchErrors,
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponses,
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData,
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchErrors,
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponses,
  UpdateOrganisationOrganisationsOrganisationIdPatchData,
  UpdateOrganisationOrganisationsOrganisationIdPatchErrors,
  UpdateOrganisationOrganisationsOrganisationIdPatchResponses,
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData,
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchErrors,
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponses,
  UpdateUserRolesUsersUserIdRolesPatchData,
  UpdateUserRolesUsersUserIdRolesPatchErrors,
  UpdateUserRolesUsersUserIdRolesPatchResponses,
  UserExistsUsersUserExistsGetData,
  UserExistsUsersUserExistsGetErrors,
  UserExistsUsersUserExistsGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Healthcheck
 */
export const healthcheckHealthcheckGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthcheckHealthcheckGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    HealthcheckHealthcheckGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/healthcheck', ...options })

/**
 * List Transcriptions
 *
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTranscriptionsTranscriptionsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListTranscriptionsTranscriptionsGetResponses,
    ListTranscriptionsTranscriptionsGetErrors,
    ThrowOnError
  >({ url: '/transcriptions', ...options })

/**
 * Create Transcription
 *
 * Start a transcription job.
 */
export const createTranscriptionTranscriptionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTranscriptionTranscriptionsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTranscriptionTranscriptionsPostResponses,
    CreateTranscriptionTranscriptionsPostErrors,
    ThrowOnError
  >({
    url: '/transcriptions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Create Recording
 */
export const createRecordingRecordingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRecordingRecordingsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRecordingRecordingsPostResponses,
    CreateRecordingRecordingsPostErrors,
    ThrowOnError
  >({
    url: '/recordings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete Transcription
 *
 * Delete a specific transcription by ID.
 */
export const deleteTranscriptionTranscriptionsTranscriptionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses,
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors,
    ThrowOnError
  >({ url: '/transcriptions/{transcription_id}', ...options })

/**
 * Get Transcription
 *
 * Get a specific transcription by ID.
 */
export const getTranscriptionTranscriptionsTranscriptionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetTranscriptionTranscriptionsTranscriptionIdGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetTranscriptionTranscriptionsTranscriptionIdGetResponses,
    GetTranscriptionTranscriptionsTranscriptionIdGetErrors,
    ThrowOnError
  >({ url: '/transcriptions/{transcription_id}', ...options })

/**
 * Get Recordings For Transcription
 */
export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).get<
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses,
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors,
      ThrowOnError
    >({ url: '/transcriptions/{transcription_id}/recordings', ...options })

/**
 * Update Transcription Title
 *
 * Update a transcription title.
 */
export const updateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponses,
    UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/title',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Rename Speaker Everywhere
 */
export const renameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).patch<
      RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponses,
      RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/speakers',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })

/**
 * Update Dialogue Entry Speaker
 */
export const updateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).patch<
      UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponses,
      UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/dialogue-entries/{entry_index}/speaker',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })

/**
 * Update Dialogue Entry Text
 */
export const updateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).patch<
      UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponses,
      UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchErrors,
      ThrowOnError
    >({
      url: '/transcriptions/{transcription_id}/dialogue-entries/{entry_index}/text',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    })

/**
 * Get User
 */
export const getUserUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserUsersMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserUsersMeGetResponses,
    GetUserUsersMeGetErrors,
    ThrowOnError
  >({ url: '/users/me', ...options })

/**
 * Update Data Retention
 *
 * Update the data retention period for the current user.
 *
 * Args:
 * data: Request body containing data_retention_days
 * current_user: The current authenticated user
 */
export const updateDataRetentionUsersDataRetentionPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateDataRetentionUsersDataRetentionPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateDataRetentionUsersDataRetentionPatchResponses,
    UpdateDataRetentionUsersDataRetentionPatchErrors,
    ThrowOnError
  >({
    url: '/users/data-retention',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * List Users
 */
export const listUsersUsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersUsersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersUsersGetResponses,
    ListUsersUsersGetErrors,
    ThrowOnError
  >({ url: '/users', ...options })

/**
 * Create User
 */
export const createUserUsersPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserUsersPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserUsersPostResponses,
    CreateUserUsersPostErrors,
    ThrowOnError
  >({
    url: '/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete User
 */
export const deleteUserUsersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteUserUsersUserIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUserUsersUserIdDeleteResponses,
    DeleteUserUsersUserIdDeleteErrors,
    ThrowOnError
  >({ url: '/users/{user_id}', ...options })

/**
 * Get Target User
 */
export const getTargetUserUsersUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTargetUserUsersUserIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTargetUserUsersUserIdGetResponses,
    GetTargetUserUsersUserIdGetErrors,
    ThrowOnError
  >({ url: '/users/{user_id}', ...options })

/**
 * Update User Roles
 */
export const updateUserRolesUsersUserIdRolesPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserRolesUsersUserIdRolesPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateUserRolesUsersUserIdRolesPatchResponses,
    UpdateUserRolesUsersUserIdRolesPatchErrors,
    ThrowOnError
  >({
    url: '/users/{user_id}/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * User Exists
 */
export const userExistsUsersUserExistsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UserExistsUsersUserExistsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserExistsUsersUserExistsGetResponses,
    UserExistsUsersUserExistsGetErrors,
    ThrowOnError
  >({ url: '/users/user/exists', ...options })

/**
 * List Minutes For Transcription
 */
export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).get<
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses,
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors,
      ThrowOnError
    >({ url: '/transcription/{transcription_id}/minutes', ...options })

/**
 * Create Minute
 */
export const createMinuteTranscriptionTranscriptionIdMinutesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateMinuteTranscriptionTranscriptionIdMinutesPostResponses,
    CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors,
    ThrowOnError
  >({
    url: '/transcription/{transcription_id}/minutes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Minute
 */
export const getMinuteMinutesMinutesIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMinuteMinutesMinutesIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetMinuteMinutesMinutesIdGetResponses,
    GetMinuteMinutesMinutesIdGetErrors,
    ThrowOnError
  >({ url: '/minutes/{minutes_id}', ...options })

/**
 * List Minute Versions
 */
export const listMinuteVersionsMinutesMinuteIdVersionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListMinuteVersionsMinutesMinuteIdVersionsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ListMinuteVersionsMinutesMinuteIdVersionsGetResponses,
    ListMinuteVersionsMinutesMinuteIdVersionsGetErrors,
    ThrowOnError
  >({ url: '/minutes/{minute_id}/versions', ...options })

/**
 * Create Minute Version
 */
export const createMinuteVersionMinutesMinuteIdVersionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateMinuteVersionMinutesMinuteIdVersionsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateMinuteVersionMinutesMinuteIdVersionsPostResponses,
    CreateMinuteVersionMinutesMinuteIdVersionsPostErrors,
    ThrowOnError
  >({
    url: '/minutes/{minute_id}/versions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete Minute Version
 */
export const deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteResponses,
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors,
    ThrowOnError
  >({ url: '/minute_versions/{minute_version_id}', ...options })

/**
 * Get Minute Version
 */
export const getMinuteVersionMinuteVersionsMinuteVersionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses,
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors,
    ThrowOnError
  >({ url: '/minute_versions/{minute_version_id}', ...options })

/**
 * Get Templates
 *
 * Get metadata for all templates.
 */
export const getTemplatesTemplatesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTemplatesTemplatesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetTemplatesTemplatesGetResponses,
    GetTemplatesTemplatesGetErrors,
    ThrowOnError
  >({ url: '/templates', ...options })

/**
 * Get User Templates
 */
export const getUserTemplatesUserTemplatesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetUserTemplatesUserTemplatesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserTemplatesUserTemplatesGetResponses,
    GetUserTemplatesUserTemplatesGetErrors,
    ThrowOnError
  >({ url: '/user-templates', ...options })

/**
 * Create User Template
 */
export const createUserTemplateUserTemplatesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserTemplateUserTemplatesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserTemplateUserTemplatesPostResponses,
    CreateUserTemplateUserTemplatesPostErrors,
    ThrowOnError
  >({
    url: '/user-templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete User Template
 */
export const deleteUserTemplateUserTemplatesTemplateIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteUserTemplateUserTemplatesTemplateIdDeleteResponses,
    DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors,
    ThrowOnError
  >({ url: '/user-templates/{template_id}', ...options })

/**
 * Get User Template
 */
export const getUserTemplateUserTemplatesTemplateIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUserTemplateUserTemplatesTemplateIdGetResponses,
    GetUserTemplateUserTemplatesTemplateIdGetErrors,
    ThrowOnError
  >({ url: '/user-templates/{template_id}', ...options })

/**
 * Edit User Template
 */
export const editUserTemplateUserTemplatesTemplateIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    EditUserTemplateUserTemplatesTemplateIdPatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    EditUserTemplateUserTemplatesTemplateIdPatchResponses,
    EditUserTemplateUserTemplatesTemplateIdPatchErrors,
    ThrowOnError
  >({
    url: '/user-templates/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Duplicate User Template
 */
export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponses,
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors,
    ThrowOnError
  >({ url: '/user-templates/{template_id}/duplicate', ...options })

/**
 * Delete Chats
 */
export const deleteChatsTranscriptionsTranscriptionIdChatDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses,
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors,
    ThrowOnError
  >({ url: '/transcriptions/{transcription_id}/chat', ...options })

/**
 * List Chat
 */
export const listChatTranscriptionsTranscriptionIdChatGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListChatTranscriptionsTranscriptionIdChatGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ListChatTranscriptionsTranscriptionIdChatGetResponses,
    ListChatTranscriptionsTranscriptionIdChatGetErrors,
    ThrowOnError
  >({ url: '/transcriptions/{transcription_id}/chat', ...options })

/**
 * Create Chat
 */
export const createChatTranscriptionsTranscriptionIdChatPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateChatTranscriptionsTranscriptionIdChatPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateChatTranscriptionsTranscriptionIdChatPostResponses,
    CreateChatTranscriptionsTranscriptionIdChatPostErrors,
    ThrowOnError
  >({
    url: '/transcriptions/{transcription_id}/chat',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete Chat
 *
 * Delete a specific transcription by ID.
 */
export const deleteChatTranscriptionsTranscriptionIdChatChatIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses,
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors,
    ThrowOnError
  >({ url: '/transcriptions/{transcription_id}/chat/{chat_id}', ...options })

/**
 * Get Chat
 */
export const getChatTranscriptionsTranscriptionIdChatChatIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses,
    GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors,
    ThrowOnError
  >({ url: '/transcriptions/{transcription_id}/chat/{chat_id}', ...options })

/**
 * List Organisations
 *
 * List all organisations. Only accessible to system admins..
 */
export const listOrganisationsOrganisationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListOrganisationsOrganisationsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListOrganisationsOrganisationsGetResponses,
    ListOrganisationsOrganisationsGetErrors,
    ThrowOnError
  >({ url: '/organisations', ...options })

/**
 * Create Organisation
 *
 * Create a new organisation. Only accessible to system admins.
 */
export const createOrganisationOrganisationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateOrganisationOrganisationsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateOrganisationOrganisationsPostResponses,
    CreateOrganisationOrganisationsPostErrors,
    ThrowOnError
  >({
    url: '/organisations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete Organisation
 *
 * Delete an organisation. Only accessible to system admins.
 */
export const deleteOrganisationOrganisationsOrganisationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteOrganisationOrganisationsOrganisationIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteOrganisationOrganisationsOrganisationIdDeleteResponses,
    DeleteOrganisationOrganisationsOrganisationIdDeleteErrors,
    ThrowOnError
  >({ url: '/organisations/{organisation_id}', ...options })

/**
 * Get Organisation
 *
 * Get organisation. Only accessible to organisation admins.
 */
export const getOrganisationOrganisationsOrganisationIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetOrganisationOrganisationsOrganisationIdGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetOrganisationOrganisationsOrganisationIdGetResponses,
    GetOrganisationOrganisationsOrganisationIdGetErrors,
    ThrowOnError
  >({ url: '/organisations/{organisation_id}', ...options })

/**
 * Update Organisation
 *
 * Update an organisation's allowed email domains. Accessible to system admins or the organisation's own admin.
 */
export const updateOrganisationOrganisationsOrganisationIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateOrganisationOrganisationsOrganisationIdPatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    UpdateOrganisationOrganisationsOrganisationIdPatchResponses,
    UpdateOrganisationOrganisationsOrganisationIdPatchErrors,
    ThrowOnError
  >({
    url: '/organisations/{organisation_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * List Organisations Users
 */
export const listOrganisationsUsersOrganisationsOrganisationIdUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponses,
    ListOrganisationsUsersOrganisationsOrganisationIdUsersGetErrors,
    ThrowOnError
  >({ url: '/organisations/{organisation_id}/users', ...options })

/**
 * Sign Out
 *
 * Sign out the user by clearing ALB auth cookies and redirecting to the IdP.
 */
export const signOutSignoutGet = <ThrowOnError extends boolean = false>(
  options?: Options<SignOutSignoutGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    SignOutSignoutGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/signout', ...options })
