// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8080' | (string & {})
}

/**
 * AgendaUsage
 */
export type AgendaUsage = 'not_used' | 'optional' | 'required'

/**
 * AiEdit
 */
export type AiEdit = {
  /**
   * Instruction
   */
  instruction: string
  /**
   * Source Id
   */
  source_id: string
}

/**
 * ChatCreateRequest
 */
export type ChatCreateRequest = {
  /**
   * User Content
   */
  user_content: string
}

/**
 * ChatCreateResponse
 */
export type ChatCreateResponse = {
  /**
   * Id
   */
  id: string
}

/**
 * ChatGetAllResponse
 */
export type ChatGetAllResponse = {
  /**
   * Chat
   */
  chat: Array<ChatGetResponse>
}

/**
 * ChatGetResponse
 */
export type ChatGetResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * User Content
   */
  user_content: string
  /**
   * Assistant Content
   */
  assistant_content: string | null
  status: JobStatus
}

/**
 * ContentSource
 */
export type ContentSource = 'manual_edit' | 'ai_edit' | 'initial_generation'

/**
 * CreateQuestion
 */
export type CreateQuestion = {
  /**
   * Position
   */
  position: number
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description: string
}

/**
 * CreateUserTemplateRequest
 */
export type CreateUserTemplateRequest = {
  /**
   * Name
   */
  name: string
  /**
   * Content
   */
  content: string
  /**
   * Description
   */
  description: string
  type: TemplateType
  /**
   * Questions
   */
  questions?: Array<CreateQuestion> | null
}

export type DataRetentionOptions = 1 | 7 | 30 | 90

/**
 * DataRetentionUpdateResponse
 */
export type DataRetentionUpdateResponse = {
  data_retention_days: DataRetentionOptions
}

/**
 * DialogueEntry
 */
export type DialogueEntry = {
  /**
   * Speaker
   */
  speaker: string
  /**
   * Text
   */
  text: string
  /**
   * Start Time
   */
  start_time: number
  /**
   * End Time
   */
  end_time: number
}

/**
 * GetUserResponse
 */
export type GetUserResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * Last Login
   */
  last_login: string
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Name
   */
  name: string | null
  /**
   * Email
   */
  email: string
  /**
   * Data Retention Days
   */
  data_retention_days: number
  /**
   * Roles
   */
  roles: Array<UserRole>
  /**
   * Organisation Id
   */
  organisation_id: string | null
}

/**
 * GuardrailResultResponse
 */
export type GuardrailResultResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Passed
   */
  passed: boolean
  /**
   * Score
   */
  score: number | null
  /**
   * Reasoning
   */
  reasoning: string | null
  /**
   * Error
   */
  error: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * JobStatus
 */
export type JobStatus =
  'awaiting_start' | 'in_progress' | 'completed' | 'failed'

/**
 * Minute
 */
export type Minute = {
  /**
   * Id
   */
  id?: string
  /**
   * Created Datetime
   */
  created_datetime?: string
  /**
   * Updated Datetime
   */
  updated_datetime?: string
  /**
   * Transcription Id
   */
  transcription_id: string
  /**
   * Template Name
   */
  template_name?: string
  /**
   * User Template Id
   */
  user_template_id?: string | null
  /**
   * Agenda
   */
  agenda?: string | null
}

/**
 * MinuteListItem
 */
export type MinuteListItem = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * Transcription Id
   */
  transcription_id: string
  /**
   * Template Name
   */
  template_name: string
  /**
   * Agenda
   */
  agenda: string | null
}

/**
 * MinuteVersion
 */
export type MinuteVersion = {
  /**
   * Id
   */
  id?: string
  /**
   * Created Datetime
   */
  created_datetime?: string
  /**
   * Updated Datetime
   */
  updated_datetime?: string
  /**
   * Minute Id
   */
  minute_id: string
  /**
   * Html Content
   */
  html_content?: string
  status?: JobStatus
  /**
   * Error
   */
  error?: string | null
  /**
   * Ai Edit Instructions
   *
   * If the content source is an AI edit, store the instruction here
   */
  ai_edit_instructions?: string | null
  content_source?: ContentSource
}

/**
 * MinuteVersionCreateRequest
 */
export type MinuteVersionCreateRequest = {
  /**
   * If the content source is an AI edit, store the instruction and source version id here
   */
  ai_edit_instructions?: AiEdit | null
  content_source: ContentSource
  /**
   * Html Content
   */
  html_content?: string
}

/**
 * MinuteVersionResponse
 */
export type MinuteVersionResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Minute Id
   */
  minute_id: string
  status: JobStatus
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Html Content
   */
  html_content: string
  /**
   * Error
   */
  error: string | null
  /**
   * Ai Edit Instructions
   */
  ai_edit_instructions: string | null
  content_source: ContentSource
  /**
   * Too Short
   */
  too_short?: boolean
  /**
   * Guardrail Results
   */
  guardrail_results?: Array<GuardrailResultResponse>
}

/**
 * MinutesCreateRequest
 */
export type MinutesCreateRequest = {
  /**
   * Template Name
   *
   * Name of the template to use for the minutes
   */
  template_name: string
  /**
   * Template Id
   *
   * Optional id of user template
   */
  template_id: string | null
  /**
   * Agenda
   *
   * The agenda for the meeting
   */
  agenda?: string | null
}

/**
 * OrganisationCreateRequest
 */
export type OrganisationCreateRequest = {
  /**
   * Name
   */
  name: string
  /**
   * Allowed Domains
   */
  allowed_domains: Array<string>
}

/**
 * OrganisationPatchRequest
 */
export type OrganisationPatchRequest = {
  /**
   * Allowed Domains
   */
  allowed_domains: Array<string>
  /**
   * Updated Datetime
   */
  updated_datetime: string
}

/**
 * OrganisationResponse
 */
export type OrganisationResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Allowed Domains
   */
  allowed_domains: Array<string>
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
}

/**
 * PaginatedTranscriptionsResponse
 *
 * Paginated response for transcriptions.
 */
export type PaginatedTranscriptionsResponse = {
  /**
   * Items
   */
  items: Array<TranscriptionMetadata>
  /**
   * Total Count
   */
  total_count: number
  /**
   * Page
   */
  page: number
  /**
   * Page Size
   */
  page_size: number
  /**
   * Total Pages
   */
  total_pages: number
}

/**
 * PaginatedUsersResponse
 */
export type PaginatedUsersResponse = {
  /**
   * Items
   */
  items: Array<GetUserResponse>
  /**
   * Total Count
   */
  total_count: number
  /**
   * Page
   */
  page: number
  /**
   * Page Size
   */
  page_size: number
  /**
   * Total Pages
   */
  total_pages: number
}

/**
 * PatchUserTemplateRequest
 */
export type PatchUserTemplateRequest = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Content
   */
  content?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Questions
   */
  questions?: Array<CreateQuestion | Question> | null
}

/**
 * Question
 */
export type Question = {
  /**
   * Position
   */
  position: number
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description: string
  /**
   * Id
   */
  id: string
}

/**
 * RecordingCreateRequest
 */
export type RecordingCreateRequest = {
  /**
   * File Extension
   */
  file_extension: string
}

/**
 * RecordingCreateResponse
 */
export type RecordingCreateResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Upload Url
   */
  upload_url: string
}

/**
 * RenameSpeakerRequest
 */
export type RenameSpeakerRequest = {
  /**
   * Original Speaker
   */
  original_speaker: string
  /**
   * New Speaker
   */
  new_speaker: string
}

/**
 * SingleRecording
 */
export type SingleRecording = {
  /**
   * Id
   */
  id: string
  /**
   * Url
   */
  url: string
  /**
   * Extension
   */
  extension: string
}

/**
 * TemplateMetadata
 */
export type TemplateMetadata = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string
  /**
   * Category
   */
  category: string
  agenda_usage: AgendaUsage
}

/**
 * TemplateResponse
 */
export type TemplateResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Updated Datetime
   */
  updated_datetime: string
  /**
   * Name
   */
  name: string
  /**
   * Content
   */
  content: string
  /**
   * Description
   */
  description: string
  type: TemplateType
  /**
   * Questions
   */
  questions: Array<Question> | null
}

/**
 * TemplateType
 */
export type TemplateType = 'document' | 'form'

/**
 * TranscriptionCreateRequest
 */
export type TranscriptionCreateRequest = {
  /**
   * Recording Id
   */
  recording_id: string
  /**
   * Template Name
   */
  template_name: string
  /**
   * Template Id
   */
  template_id?: string | null
  /**
   * Agenda
   */
  agenda?: string | null
  /**
   * Title
   */
  title?: string | null
}

/**
 * TranscriptionCreateResponse
 */
export type TranscriptionCreateResponse = {
  /**
   * Id
   */
  id: string
}

/**
 * TranscriptionGetResponse
 */
export type TranscriptionGetResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Title
   */
  title: string | null
  /**
   * Dialogue Entries
   */
  dialogue_entries: Array<DialogueEntry> | null
  status: JobStatus
  /**
   * Created Datetime
   */
  created_datetime: string
}

/**
 * TranscriptionMetadata
 *
 * Pydantic model for transcription metadata.
 */
export type TranscriptionMetadata = {
  /**
   * Id
   */
  id: string
  /**
   * Created Datetime
   */
  created_datetime: string
  /**
   * Title
   */
  title?: string | null
  /**
   * Text
   */
  text: string
  status: JobStatus
}

/**
 * UpdateDialogueEntrySpeakerRequest
 */
export type UpdateDialogueEntrySpeakerRequest = {
  /**
   * New Text
   */
  new_speaker: string
  /**
   * Expected Text
   */
  expected_text?: string | null
  /**
   * Expected Speaker
   */
  expected_speaker?: string | null
  /**
   * Expected Start Time
   */
  expected_start_time?: number | null
  /**
   * Expected End Time
   */
  expected_end_time?: number | null
}

/**
 * UpdateDialogueEntryTextRequest
 */
export type UpdateDialogueEntryTextRequest = {
  /**
   * New Text
   */
  new_text: string
  /**
   * Expected Text
   */
  expected_text?: string | null
  /**
   * Expected Speaker
   */
  expected_speaker?: string | null
  /**
   * Expected Start Time
   */
  expected_start_time?: number | null
  /**
   * Expected End Time
   */
  expected_end_time?: number | null
}

/**
 * UpdateTranscriptionTitleRequest
 */
export type UpdateTranscriptionTitleRequest = {
  /**
   * Title
   */
  title?: string | null
}

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Email
   */
  email: string
  /**
   * Organisation Id
   */
  organisation_id: string
}

/**
 * UserExistsResponse
 */
export type UserExistsResponse = {
  /**
   * Exists
   */
  exists: boolean
}

/**
 * UserRole
 */
export type UserRole =
  'standard_user' | 'local_authority_admin' | 'mhclg_support_admin'

/**
 * UserUpdateRoles
 */
export type UserUpdateRoles = {
  /**
   * Roles
   */
  roles: Array<UserRole>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type HealthcheckHealthcheckGetData = {
  body?: never
  path?: never
  query?: never
  url: '/healthcheck'
}

export type HealthcheckHealthcheckGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ListTranscriptionsTranscriptionsGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: {
    /**
     * Page
     *
     * Page number (starts from 1)
     */
    page?: number
    /**
     * Page Size
     *
     * Number of items per page
     */
    page_size?: number
  }
  url: '/transcriptions'
}

export type ListTranscriptionsTranscriptionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListTranscriptionsTranscriptionsGetError =
  ListTranscriptionsTranscriptionsGetErrors[keyof ListTranscriptionsTranscriptionsGetErrors]

export type ListTranscriptionsTranscriptionsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedTranscriptionsResponse
}

export type ListTranscriptionsTranscriptionsGetResponse =
  ListTranscriptionsTranscriptionsGetResponses[keyof ListTranscriptionsTranscriptionsGetResponses]

export type CreateTranscriptionTranscriptionsPostData = {
  body: TranscriptionCreateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/transcriptions'
}

export type CreateTranscriptionTranscriptionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateTranscriptionTranscriptionsPostError =
  CreateTranscriptionTranscriptionsPostErrors[keyof CreateTranscriptionTranscriptionsPostErrors]

export type CreateTranscriptionTranscriptionsPostResponses = {
  /**
   * Successful Response
   */
  201: TranscriptionCreateResponse
}

export type CreateTranscriptionTranscriptionsPostResponse =
  CreateTranscriptionTranscriptionsPostResponses[keyof CreateTranscriptionTranscriptionsPostResponses]

export type CreateRecordingRecordingsPostData = {
  body: RecordingCreateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/recordings'
}

export type CreateRecordingRecordingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateRecordingRecordingsPostError =
  CreateRecordingRecordingsPostErrors[keyof CreateRecordingRecordingsPostErrors]

export type CreateRecordingRecordingsPostResponses = {
  /**
   * Successful Response
   */
  200: RecordingCreateResponse
}

export type CreateRecordingRecordingsPostResponse =
  CreateRecordingRecordingsPostResponses[keyof CreateRecordingRecordingsPostResponses]

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}'
}

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError =
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors[keyof DeleteTranscriptionTranscriptionsTranscriptionIdDeleteErrors]

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse =
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses[keyof DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponses]

export type GetTranscriptionTranscriptionsTranscriptionIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}'
}

export type GetTranscriptionTranscriptionsTranscriptionIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetTranscriptionTranscriptionsTranscriptionIdGetError =
  GetTranscriptionTranscriptionsTranscriptionIdGetErrors[keyof GetTranscriptionTranscriptionsTranscriptionIdGetErrors]

export type GetTranscriptionTranscriptionsTranscriptionIdGetResponses = {
  /**
   * Successful Response
   */
  200: TranscriptionGetResponse
}

export type GetTranscriptionTranscriptionsTranscriptionIdGetResponse =
  GetTranscriptionTranscriptionsTranscriptionIdGetResponses[keyof GetTranscriptionTranscriptionsTranscriptionIdGetResponses]

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData =
  {
    body?: never
    headers?: {
      /**
       * X-Amzn-Oidc-Data
       */
      'x-amzn-oidc-data'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/recordings'
  }

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetError =
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors[keyof GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetErrors]

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses =
  {
    /**
     * Response Get Recordings For Transcription Transcriptions  Transcription Id  Recordings Get
     *
     * Successful Response
     */
    200: Array<SingleRecording>
  }

export type GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse =
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses[keyof GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponses]

export type UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData =
  {
    body: UpdateTranscriptionTitleRequest
    headers?: {
      /**
       * X-Amzn-Oidc-Data
       */
      'x-amzn-oidc-data'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/title'
  }

export type UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchError =
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchErrors[keyof UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchErrors]

export type UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponse =
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponses[keyof UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponses]

export type RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData =
  {
    body: RenameSpeakerRequest
    headers?: {
      /**
       * X-Amzn-Oidc-Data
       */
      'x-amzn-oidc-data'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcriptions/{transcription_id}/speakers'
  }

export type RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchError =
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchErrors[keyof RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchErrors]

export type RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponse =
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponses[keyof RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponses]

export type UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData =
  {
    body: UpdateDialogueEntrySpeakerRequest
    headers?: {
      /**
       * X-Amzn-Oidc-Data
       */
      'x-amzn-oidc-data'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
      /**
       * Entry Index
       */
      entry_index: number
    }
    query?: never
    url: '/transcriptions/{transcription_id}/dialogue-entries/{entry_index}/speaker'
  }

export type UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchError =
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchErrors[keyof UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchErrors]

export type UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponse =
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponses[keyof UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponses]

export type UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData =
  {
    body: UpdateDialogueEntryTextRequest
    headers?: {
      /**
       * X-Amzn-Oidc-Data
       */
      'x-amzn-oidc-data'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
      /**
       * Entry Index
       */
      entry_index: number
    }
    query?: never
    url: '/transcriptions/{transcription_id}/dialogue-entries/{entry_index}/text'
  }

export type UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchError =
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchErrors[keyof UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchErrors]

export type UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponses =
  {
    /**
     * Successful Response
     */
    204: void
  }

export type UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponse =
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponses[keyof UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponses]

export type GetUserUsersMeGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/users/me'
}

export type GetUserUsersMeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserUsersMeGetError =
  GetUserUsersMeGetErrors[keyof GetUserUsersMeGetErrors]

export type GetUserUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type GetUserUsersMeGetResponse =
  GetUserUsersMeGetResponses[keyof GetUserUsersMeGetResponses]

export type UpdateDataRetentionUsersDataRetentionPatchData = {
  body: DataRetentionUpdateResponse
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/users/data-retention'
}

export type UpdateDataRetentionUsersDataRetentionPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateDataRetentionUsersDataRetentionPatchError =
  UpdateDataRetentionUsersDataRetentionPatchErrors[keyof UpdateDataRetentionUsersDataRetentionPatchErrors]

export type UpdateDataRetentionUsersDataRetentionPatchResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type UpdateDataRetentionUsersDataRetentionPatchResponse =
  UpdateDataRetentionUsersDataRetentionPatchResponses[keyof UpdateDataRetentionUsersDataRetentionPatchResponses]

export type ListUsersUsersGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Page Size
     */
    page_size?: number
  }
  url: '/users'
}

export type ListUsersUsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListUsersUsersGetError =
  ListUsersUsersGetErrors[keyof ListUsersUsersGetErrors]

export type ListUsersUsersGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedUsersResponse
}

export type ListUsersUsersGetResponse =
  ListUsersUsersGetResponses[keyof ListUsersUsersGetResponses]

export type CreateUserUsersPostData = {
  body: UserCreate
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/users'
}

export type CreateUserUsersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateUserUsersPostError =
  CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors]

export type CreateUserUsersPostResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type CreateUserUsersPostResponse =
  CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses]

export type DeleteUserUsersUserIdDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/users/{user_id}'
}

export type DeleteUserUsersUserIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteUserUsersUserIdDeleteError =
  DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors]

export type DeleteUserUsersUserIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteUserUsersUserIdDeleteResponse =
  DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses]

export type GetTargetUserUsersUserIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/users/{user_id}'
}

export type GetTargetUserUsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetTargetUserUsersUserIdGetError =
  GetTargetUserUsersUserIdGetErrors[keyof GetTargetUserUsersUserIdGetErrors]

export type GetTargetUserUsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type GetTargetUserUsersUserIdGetResponse =
  GetTargetUserUsersUserIdGetResponses[keyof GetTargetUserUsersUserIdGetResponses]

export type UpdateUserRolesUsersUserIdRolesPatchData = {
  body: UserUpdateRoles
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/users/{user_id}/roles'
}

export type UpdateUserRolesUsersUserIdRolesPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateUserRolesUsersUserIdRolesPatchError =
  UpdateUserRolesUsersUserIdRolesPatchErrors[keyof UpdateUserRolesUsersUserIdRolesPatchErrors]

export type UpdateUserRolesUsersUserIdRolesPatchResponses = {
  /**
   * Successful Response
   */
  200: GetUserResponse
}

export type UpdateUserRolesUsersUserIdRolesPatchResponse =
  UpdateUserRolesUsersUserIdRolesPatchResponses[keyof UpdateUserRolesUsersUserIdRolesPatchResponses]

export type UserExistsUsersUserExistsGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query: {
    /**
     * Email
     */
    email: string
    /**
     * Organisation Id
     */
    organisation_id: string
  }
  url: '/users/user/exists'
}

export type UserExistsUsersUserExistsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UserExistsUsersUserExistsGetError =
  UserExistsUsersUserExistsGetErrors[keyof UserExistsUsersUserExistsGetErrors]

export type UserExistsUsersUserExistsGetResponses = {
  /**
   * Successful Response
   */
  200: UserExistsResponse
}

export type UserExistsUsersUserExistsGetResponse =
  UserExistsUsersUserExistsGetResponses[keyof UserExistsUsersUserExistsGetResponses]

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData =
  {
    body?: never
    headers?: {
      /**
       * X-Amzn-Oidc-Data
       */
      'x-amzn-oidc-data'?: string | null
    }
    path: {
      /**
       * Transcription Id
       */
      transcription_id: string
    }
    query?: never
    url: '/transcription/{transcription_id}/minutes'
  }

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetError =
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors[keyof ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetErrors]

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses =
  {
    /**
     * Response List Minutes For Transcription Transcription  Transcription Id  Minutes Get
     *
     * Successful Response
     */
    200: Array<MinuteListItem>
  }

export type ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse =
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses[keyof ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponses]

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostData = {
  body: MinutesCreateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcription/{transcription_id}/minutes'
}

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostError =
  CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors[keyof CreateMinuteTranscriptionTranscriptionIdMinutesPostErrors]

export type CreateMinuteTranscriptionTranscriptionIdMinutesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetMinuteMinutesMinutesIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Minutes Id
     */
    minutes_id: string
  }
  query?: never
  url: '/minutes/{minutes_id}'
}

export type GetMinuteMinutesMinutesIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetMinuteMinutesMinutesIdGetError =
  GetMinuteMinutesMinutesIdGetErrors[keyof GetMinuteMinutesMinutesIdGetErrors]

export type GetMinuteMinutesMinutesIdGetResponses = {
  /**
   * Successful Response
   */
  200: Minute
}

export type GetMinuteMinutesMinutesIdGetResponse =
  GetMinuteMinutesMinutesIdGetResponses[keyof GetMinuteMinutesMinutesIdGetResponses]

export type ListMinuteVersionsMinutesMinuteIdVersionsGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Minute Id
     */
    minute_id: string
  }
  query?: never
  url: '/minutes/{minute_id}/versions'
}

export type ListMinuteVersionsMinutesMinuteIdVersionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListMinuteVersionsMinutesMinuteIdVersionsGetError =
  ListMinuteVersionsMinutesMinuteIdVersionsGetErrors[keyof ListMinuteVersionsMinutesMinuteIdVersionsGetErrors]

export type ListMinuteVersionsMinutesMinuteIdVersionsGetResponses = {
  /**
   * Response List Minute Versions Minutes  Minute Id  Versions Get
   *
   * Successful Response
   */
  200: Array<MinuteVersionResponse>
}

export type ListMinuteVersionsMinutesMinuteIdVersionsGetResponse =
  ListMinuteVersionsMinutesMinuteIdVersionsGetResponses[keyof ListMinuteVersionsMinutesMinuteIdVersionsGetResponses]

export type CreateMinuteVersionMinutesMinuteIdVersionsPostData = {
  body: MinuteVersionCreateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Minute Id
     */
    minute_id: string
  }
  query?: never
  url: '/minutes/{minute_id}/versions'
}

export type CreateMinuteVersionMinutesMinuteIdVersionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateMinuteVersionMinutesMinuteIdVersionsPostError =
  CreateMinuteVersionMinutesMinuteIdVersionsPostErrors[keyof CreateMinuteVersionMinutesMinuteIdVersionsPostErrors]

export type CreateMinuteVersionMinutesMinuteIdVersionsPostResponses = {
  /**
   * Successful Response
   */
  200: MinuteVersionResponse
}

export type CreateMinuteVersionMinutesMinuteIdVersionsPostResponse =
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponses[keyof CreateMinuteVersionMinutesMinuteIdVersionsPostResponses]

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Minute Version Id
     */
    minute_version_id: string
  }
  query?: never
  url: '/minute_versions/{minute_version_id}'
}

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError =
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors[keyof DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteErrors]

export type DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Minute Version Id
     */
    minute_version_id: string
  }
  query?: never
  url: '/minute_versions/{minute_version_id}'
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetError =
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors[keyof GetMinuteVersionMinuteVersionsMinuteVersionIdGetErrors]

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses = {
  /**
   * Successful Response
   */
  200: MinuteVersion
}

export type GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse =
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses[keyof GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponses]

export type GetTemplatesTemplatesGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/templates'
}

export type GetTemplatesTemplatesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetTemplatesTemplatesGetError =
  GetTemplatesTemplatesGetErrors[keyof GetTemplatesTemplatesGetErrors]

export type GetTemplatesTemplatesGetResponses = {
  /**
   * Response Get Templates Templates Get
   *
   * Successful Response
   */
  200: Array<TemplateMetadata>
}

export type GetTemplatesTemplatesGetResponse =
  GetTemplatesTemplatesGetResponses[keyof GetTemplatesTemplatesGetResponses]

export type GetUserTemplatesUserTemplatesGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/user-templates'
}

export type GetUserTemplatesUserTemplatesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserTemplatesUserTemplatesGetError =
  GetUserTemplatesUserTemplatesGetErrors[keyof GetUserTemplatesUserTemplatesGetErrors]

export type GetUserTemplatesUserTemplatesGetResponses = {
  /**
   * Response Get User Templates User Templates Get
   *
   * Successful Response
   */
  200: Array<TemplateResponse>
}

export type GetUserTemplatesUserTemplatesGetResponse =
  GetUserTemplatesUserTemplatesGetResponses[keyof GetUserTemplatesUserTemplatesGetResponses]

export type CreateUserTemplateUserTemplatesPostData = {
  body: CreateUserTemplateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/user-templates'
}

export type CreateUserTemplateUserTemplatesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateUserTemplateUserTemplatesPostError =
  CreateUserTemplateUserTemplatesPostErrors[keyof CreateUserTemplateUserTemplatesPostErrors]

export type CreateUserTemplateUserTemplatesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}'
}

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteError =
  DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors[keyof DeleteUserTemplateUserTemplatesTemplateIdDeleteErrors]

export type DeleteUserTemplateUserTemplatesTemplateIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetUserTemplateUserTemplatesTemplateIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}'
}

export type GetUserTemplateUserTemplatesTemplateIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserTemplateUserTemplatesTemplateIdGetError =
  GetUserTemplateUserTemplatesTemplateIdGetErrors[keyof GetUserTemplateUserTemplatesTemplateIdGetErrors]

export type GetUserTemplateUserTemplatesTemplateIdGetResponses = {
  /**
   * Successful Response
   */
  200: TemplateResponse
}

export type GetUserTemplateUserTemplatesTemplateIdGetResponse =
  GetUserTemplateUserTemplatesTemplateIdGetResponses[keyof GetUserTemplateUserTemplatesTemplateIdGetResponses]

export type EditUserTemplateUserTemplatesTemplateIdPatchData = {
  body: PatchUserTemplateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}'
}

export type EditUserTemplateUserTemplatesTemplateIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type EditUserTemplateUserTemplatesTemplateIdPatchError =
  EditUserTemplateUserTemplatesTemplateIdPatchErrors[keyof EditUserTemplateUserTemplatesTemplateIdPatchErrors]

export type EditUserTemplateUserTemplatesTemplateIdPatchResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/user-templates/{template_id}/duplicate'
}

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError =
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors[keyof DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostErrors]

export type DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown
  }

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat'
}

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteError =
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors[keyof DeleteChatsTranscriptionsTranscriptionIdChatDeleteErrors]

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse =
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses[keyof DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponses]

export type ListChatTranscriptionsTranscriptionIdChatGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat'
}

export type ListChatTranscriptionsTranscriptionIdChatGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatTranscriptionsTranscriptionIdChatGetError =
  ListChatTranscriptionsTranscriptionIdChatGetErrors[keyof ListChatTranscriptionsTranscriptionIdChatGetErrors]

export type ListChatTranscriptionsTranscriptionIdChatGetResponses = {
  /**
   * Successful Response
   */
  200: ChatGetAllResponse
}

export type ListChatTranscriptionsTranscriptionIdChatGetResponse =
  ListChatTranscriptionsTranscriptionIdChatGetResponses[keyof ListChatTranscriptionsTranscriptionIdChatGetResponses]

export type CreateChatTranscriptionsTranscriptionIdChatPostData = {
  body: ChatCreateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat'
}

export type CreateChatTranscriptionsTranscriptionIdChatPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateChatTranscriptionsTranscriptionIdChatPostError =
  CreateChatTranscriptionsTranscriptionIdChatPostErrors[keyof CreateChatTranscriptionsTranscriptionIdChatPostErrors]

export type CreateChatTranscriptionsTranscriptionIdChatPostResponses = {
  /**
   * Successful Response
   */
  201: ChatCreateResponse
}

export type CreateChatTranscriptionsTranscriptionIdChatPostResponse =
  CreateChatTranscriptionsTranscriptionIdChatPostResponses[keyof CreateChatTranscriptionsTranscriptionIdChatPostResponses]

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat/{chat_id}'
}

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError =
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors[keyof DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteErrors]

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse =
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses[keyof DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponses]

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Transcription Id
     */
    transcription_id: string
    /**
     * Chat Id
     */
    chat_id: string
  }
  query?: never
  url: '/transcriptions/{transcription_id}/chat/{chat_id}'
}

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetError =
  GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors[keyof GetChatTranscriptionsTranscriptionIdChatChatIdGetErrors]

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses = {
  /**
   * Successful Response
   */
  200: ChatGetResponse
}

export type GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse =
  GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses[keyof GetChatTranscriptionsTranscriptionIdChatChatIdGetResponses]

export type ListOrganisationsOrganisationsGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/organisations'
}

export type ListOrganisationsOrganisationsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListOrganisationsOrganisationsGetError =
  ListOrganisationsOrganisationsGetErrors[keyof ListOrganisationsOrganisationsGetErrors]

export type ListOrganisationsOrganisationsGetResponses = {
  /**
   * Response List Organisations Organisations Get
   *
   * Successful Response
   */
  200: Array<OrganisationResponse>
}

export type ListOrganisationsOrganisationsGetResponse =
  ListOrganisationsOrganisationsGetResponses[keyof ListOrganisationsOrganisationsGetResponses]

export type CreateOrganisationOrganisationsPostData = {
  body: OrganisationCreateRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path?: never
  query?: never
  url: '/organisations'
}

export type CreateOrganisationOrganisationsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateOrganisationOrganisationsPostError =
  CreateOrganisationOrganisationsPostErrors[keyof CreateOrganisationOrganisationsPostErrors]

export type CreateOrganisationOrganisationsPostResponses = {
  /**
   * Successful Response
   */
  201: OrganisationResponse
}

export type CreateOrganisationOrganisationsPostResponse =
  CreateOrganisationOrganisationsPostResponses[keyof CreateOrganisationOrganisationsPostResponses]

export type DeleteOrganisationOrganisationsOrganisationIdDeleteData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Organisation Id
     */
    organisation_id: string
  }
  query?: never
  url: '/organisations/{organisation_id}'
}

export type DeleteOrganisationOrganisationsOrganisationIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteOrganisationOrganisationsOrganisationIdDeleteError =
  DeleteOrganisationOrganisationsOrganisationIdDeleteErrors[keyof DeleteOrganisationOrganisationsOrganisationIdDeleteErrors]

export type DeleteOrganisationOrganisationsOrganisationIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteOrganisationOrganisationsOrganisationIdDeleteResponse =
  DeleteOrganisationOrganisationsOrganisationIdDeleteResponses[keyof DeleteOrganisationOrganisationsOrganisationIdDeleteResponses]

export type GetOrganisationOrganisationsOrganisationIdGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Organisation Id
     */
    organisation_id: string
  }
  query?: never
  url: '/organisations/{organisation_id}'
}

export type GetOrganisationOrganisationsOrganisationIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetOrganisationOrganisationsOrganisationIdGetError =
  GetOrganisationOrganisationsOrganisationIdGetErrors[keyof GetOrganisationOrganisationsOrganisationIdGetErrors]

export type GetOrganisationOrganisationsOrganisationIdGetResponses = {
  /**
   * Successful Response
   */
  200: OrganisationResponse
}

export type GetOrganisationOrganisationsOrganisationIdGetResponse =
  GetOrganisationOrganisationsOrganisationIdGetResponses[keyof GetOrganisationOrganisationsOrganisationIdGetResponses]

export type UpdateOrganisationOrganisationsOrganisationIdPatchData = {
  body: OrganisationPatchRequest
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Organisation Id
     */
    organisation_id: string
  }
  query?: never
  url: '/organisations/{organisation_id}'
}

export type UpdateOrganisationOrganisationsOrganisationIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateOrganisationOrganisationsOrganisationIdPatchError =
  UpdateOrganisationOrganisationsOrganisationIdPatchErrors[keyof UpdateOrganisationOrganisationsOrganisationIdPatchErrors]

export type UpdateOrganisationOrganisationsOrganisationIdPatchResponses = {
  /**
   * Successful Response
   */
  200: OrganisationResponse
}

export type UpdateOrganisationOrganisationsOrganisationIdPatchResponse =
  UpdateOrganisationOrganisationsOrganisationIdPatchResponses[keyof UpdateOrganisationOrganisationsOrganisationIdPatchResponses]

export type ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData = {
  body?: never
  headers?: {
    /**
     * X-Amzn-Oidc-Data
     */
    'x-amzn-oidc-data'?: string | null
  }
  path: {
    /**
     * Organisation Id
     */
    organisation_id: string
  }
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Page Size
     */
    page_size?: number
  }
  url: '/organisations/{organisation_id}/users'
}

export type ListOrganisationsUsersOrganisationsOrganisationIdUsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListOrganisationsUsersOrganisationsOrganisationIdUsersGetError =
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetErrors[keyof ListOrganisationsUsersOrganisationsOrganisationIdUsersGetErrors]

export type ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponses =
  {
    /**
     * Successful Response
     */
    200: PaginatedUsersResponse
  }

export type ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponse =
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponses[keyof ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponses]

export type SignOutSignoutGetData = {
  body?: never
  path?: never
  query?: never
  url: '/signout'
}

export type SignOutSignoutGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
