name: validate-terraform

on:
  pull_request:
  push:
    branches: [development, main]

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/terraform-validate.yml
    secrets: inherit
    permissions:
      contents: read
  plan:
    needs: validate
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      pull-requests: write