// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  acceptTermsOfUseUsersTermsOfUsePost,
  createChatTranscriptionsTranscriptionIdChatPost,
  createMinuteTranscriptionTranscriptionIdMinutesPost,
  createMinuteVersionMinutesMinuteIdVersionsPost,
  createOrganisationOrganisationsPost,
  createRecordingRecordingsPost,
  createTranscriptionTranscriptionsPost,
  createUserTemplateUserTemplatesPost,
  createUserUsersPost,
  deleteChatsTranscriptionsTranscriptionIdChatDelete,
  deleteChatTranscriptionsTranscriptionIdChatChatIdDelete,
  deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete,
  deleteOrganisationOrganisationsOrganisationIdDelete,
  deleteTranscriptionTranscriptionsTranscriptionIdDelete,
  deleteUserTemplateUserTemplatesTemplateIdDelete,
  deleteUserUsersUserIdDelete,
  duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost,
  editUserTemplateUserTemplatesTemplateIdPatch,
  getChatTranscriptionsTranscriptionIdChatChatIdGet,
  getMinuteMinutesMinutesIdGet,
  getMinuteVersionMinuteVersionsMinuteVersionIdGet,
  getOrganisationOrganisationsOrganisationIdGet,
  getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet,
  getTargetUserUsersUserIdGet,
  getTemplatesTemplatesGet,
  getTranscriptionTranscriptionsTranscriptionIdGet,
  getUserTemplatesUserTemplatesGet,
  getUserTemplateUserTemplatesTemplateIdGet,
  getUserUsersMeGet,
  healthcheckHealthcheckGet,
  listChatTranscriptionsTranscriptionIdChatGet,
  listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet,
  listMinuteVersionsMinutesMinuteIdVersionsGet,
  listOrganisationsOrganisationsGet,
  listOrganisationsUsersOrganisationsOrganisationIdUsersGet,
  listTranscriptionsTranscriptionsGet,
  listUsersUsersGet,
  type Options,
  renameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatch,
  signOutSignoutGet,
  updateDataRetentionUsersDataRetentionPatch,
  updateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatch,
  updateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatch,
  updateOrganisationOrganisationsOrganisationIdPatch,
  updateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatch,
  updateUserRolesUsersUserIdRolesPatch,
  userExistsUsersUserExistsGet,
} from '../sdk.gen'
import type {
  AcceptTermsOfUseUsersTermsOfUsePostData,
  AcceptTermsOfUseUsersTermsOfUsePostError,
  AcceptTermsOfUseUsersTermsOfUsePostResponse,
  CreateChatTranscriptionsTranscriptionIdChatPostData,
  CreateChatTranscriptionsTranscriptionIdChatPostError,
  CreateChatTranscriptionsTranscriptionIdChatPostResponse,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
  CreateMinuteVersionMinutesMinuteIdVersionsPostData,
  CreateMinuteVersionMinutesMinuteIdVersionsPostError,
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
  CreateOrganisationOrganisationsPostData,
  CreateOrganisationOrganisationsPostError,
  CreateOrganisationOrganisationsPostResponse,
  CreateRecordingRecordingsPostData,
  CreateRecordingRecordingsPostError,
  CreateRecordingRecordingsPostResponse,
  CreateTranscriptionTranscriptionsPostData,
  CreateTranscriptionTranscriptionsPostError,
  CreateTranscriptionTranscriptionsPostResponse,
  CreateUserTemplateUserTemplatesPostData,
  CreateUserTemplateUserTemplatesPostError,
  CreateUserUsersPostData,
  CreateUserUsersPostError,
  CreateUserUsersPostResponse,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
  DeleteOrganisationOrganisationsOrganisationIdDeleteData,
  DeleteOrganisationOrganisationsOrganisationIdDeleteError,
  DeleteOrganisationOrganisationsOrganisationIdDeleteResponse,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
  DeleteUserUsersUserIdDeleteData,
  DeleteUserUsersUserIdDeleteError,
  DeleteUserUsersUserIdDeleteResponse,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
  EditUserTemplateUserTemplatesTemplateIdPatchData,
  EditUserTemplateUserTemplatesTemplateIdPatchError,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetError,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse,
  GetMinuteMinutesMinutesIdGetData,
  GetMinuteMinutesMinutesIdGetError,
  GetMinuteMinutesMinutesIdGetResponse,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetError,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse,
  GetOrganisationOrganisationsOrganisationIdGetData,
  GetOrganisationOrganisationsOrganisationIdGetError,
  GetOrganisationOrganisationsOrganisationIdGetResponse,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetError,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse,
  GetTargetUserUsersUserIdGetData,
  GetTargetUserUsersUserIdGetError,
  GetTargetUserUsersUserIdGetResponse,
  GetTemplatesTemplatesGetData,
  GetTemplatesTemplatesGetError,
  GetTemplatesTemplatesGetResponse,
  GetTranscriptionTranscriptionsTranscriptionIdGetData,
  GetTranscriptionTranscriptionsTranscriptionIdGetError,
  GetTranscriptionTranscriptionsTranscriptionIdGetResponse,
  GetUserTemplatesUserTemplatesGetData,
  GetUserTemplatesUserTemplatesGetError,
  GetUserTemplatesUserTemplatesGetResponse,
  GetUserTemplateUserTemplatesTemplateIdGetData,
  GetUserTemplateUserTemplatesTemplateIdGetError,
  GetUserTemplateUserTemplatesTemplateIdGetResponse,
  GetUserUsersMeGetData,
  GetUserUsersMeGetError,
  GetUserUsersMeGetResponse,
  HealthcheckHealthcheckGetData,
  ListChatTranscriptionsTranscriptionIdChatGetData,
  ListChatTranscriptionsTranscriptionIdChatGetError,
  ListChatTranscriptionsTranscriptionIdChatGetResponse,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetError,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse,
  ListMinuteVersionsMinutesMinuteIdVersionsGetData,
  ListMinuteVersionsMinutesMinuteIdVersionsGetError,
  ListMinuteVersionsMinutesMinuteIdVersionsGetResponse,
  ListOrganisationsOrganisationsGetData,
  ListOrganisationsOrganisationsGetError,
  ListOrganisationsOrganisationsGetResponse,
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData,
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetError,
  ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponse,
  ListTranscriptionsTranscriptionsGetData,
  ListTranscriptionsTranscriptionsGetError,
  ListTranscriptionsTranscriptionsGetResponse,
  ListUsersUsersGetData,
  ListUsersUsersGetError,
  ListUsersUsersGetResponse,
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData,
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchError,
  RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponse,
  SignOutSignoutGetData,
  UpdateDataRetentionUsersDataRetentionPatchData,
  UpdateDataRetentionUsersDataRetentionPatchError,
  UpdateDataRetentionUsersDataRetentionPatchResponse,
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData,
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchError,
  UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponse,
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData,
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchError,
  UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponse,
  UpdateOrganisationOrganisationsOrganisationIdPatchData,
  UpdateOrganisationOrganisationsOrganisationIdPatchError,
  UpdateOrganisationOrganisationsOrganisationIdPatchResponse,
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData,
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchError,
  UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponse,
  UpdateUserRolesUsersUserIdRolesPatchData,
  UpdateUserRolesUsersUserIdRolesPatchError,
  UpdateUserRolesUsersUserIdRolesPatchResponse,
  UserExistsUsersUserExistsGetData,
  UserExistsUsersUserExistsGetError,
  UserExistsUsersUserExistsGetResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const healthcheckHealthcheckGetQueryKey = (
  options?: Options<HealthcheckHealthcheckGetData>
) => createQueryKey('healthcheckHealthcheckGet', options)

/**
 * Healthcheck
 */
export const healthcheckHealthcheckGetOptions = (
  options?: Options<HealthcheckHealthcheckGetData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthcheckHealthcheckGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthcheckHealthcheckGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthcheckHealthcheckGetQueryKey(options),
  })

export const listTranscriptionsTranscriptionsGetQueryKey = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) => createQueryKey('listTranscriptionsTranscriptionsGet', options)

/**
 * List Transcriptions
 *
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGetOptions = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) =>
  queryOptions<
    ListTranscriptionsTranscriptionsGetResponse,
    ListTranscriptionsTranscriptionsGetError,
    ListTranscriptionsTranscriptionsGetResponse,
    ReturnType<typeof listTranscriptionsTranscriptionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTranscriptionsTranscriptionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listTranscriptionsTranscriptionsGetQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listTranscriptionsTranscriptionsGetInfiniteQueryKey = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
): QueryKey<Options<ListTranscriptionsTranscriptionsGetData>> =>
  createQueryKey('listTranscriptionsTranscriptionsGet', options, true)

/**
 * List Transcriptions
 *
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGetInfiniteOptions = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) =>
  infiniteQueryOptions<
    ListTranscriptionsTranscriptionsGetResponse,
    ListTranscriptionsTranscriptionsGetError,
    InfiniteData<ListTranscriptionsTranscriptionsGetResponse>,
    QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listTranscriptionsTranscriptionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listTranscriptionsTranscriptionsGetInfiniteQueryKey(options),
    }
  )

/**
 * Create Transcription
 *
 * Start a transcription job.
 */
export const createTranscriptionTranscriptionsPostMutation = (
  options?: Partial<Options<CreateTranscriptionTranscriptionsPostData>>
): UseMutationOptions<
  CreateTranscriptionTranscriptionsPostResponse,
  CreateTranscriptionTranscriptionsPostError,
  Options<CreateTranscriptionTranscriptionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTranscriptionTranscriptionsPostResponse,
    CreateTranscriptionTranscriptionsPostError,
    Options<CreateTranscriptionTranscriptionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTranscriptionTranscriptionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Create Recording
 */
export const createRecordingRecordingsPostMutation = (
  options?: Partial<Options<CreateRecordingRecordingsPostData>>
): UseMutationOptions<
  CreateRecordingRecordingsPostResponse,
  CreateRecordingRecordingsPostError,
  Options<CreateRecordingRecordingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRecordingRecordingsPostResponse,
    CreateRecordingRecordingsPostError,
    Options<CreateRecordingRecordingsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRecordingRecordingsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Transcription
 *
 * Delete a specific transcription by ID.
 */
export const deleteTranscriptionTranscriptionsTranscriptionIdDeleteMutation = (
  options?: Partial<
    Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
  >
): UseMutationOptions<
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
  Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
    Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteTranscriptionTranscriptionsTranscriptionIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getTranscriptionTranscriptionsTranscriptionIdGetQueryKey = (
  options: Options<GetTranscriptionTranscriptionsTranscriptionIdGetData>
) => createQueryKey('getTranscriptionTranscriptionsTranscriptionIdGet', options)

/**
 * Get Transcription
 *
 * Get a specific transcription by ID.
 */
export const getTranscriptionTranscriptionsTranscriptionIdGetOptions = (
  options: Options<GetTranscriptionTranscriptionsTranscriptionIdGetData>
) =>
  queryOptions<
    GetTranscriptionTranscriptionsTranscriptionIdGetResponse,
    GetTranscriptionTranscriptionsTranscriptionIdGetError,
    GetTranscriptionTranscriptionsTranscriptionIdGetResponse,
    ReturnType<typeof getTranscriptionTranscriptionsTranscriptionIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTranscriptionTranscriptionsTranscriptionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTranscriptionTranscriptionsTranscriptionIdGetQueryKey(options),
  })

export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey =
  (
    options: Options<GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData>
  ) =>
    createQueryKey(
      'getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet',
      options
    )

/**
 * Get Recordings For Transcription
 */
export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetOptions =
  (
    options: Options<GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData>
  ) =>
    queryOptions<
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse,
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetError,
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse,
      ReturnType<
        typeof getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey(
          options
        ),
    })

/**
 * Update Transcription Title
 *
 * Update a transcription title.
 */
export const updateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchMutation =
  (
    options?: Partial<
      Options<UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData>
    >
  ): UseMutationOptions<
    UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponse,
    UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchError,
    Options<UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData>
  > => {
    const mutationOptions: UseMutationOptions<
      UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchResponse,
      UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchError,
      Options<UpdateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatchData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await updateTranscriptionTitleTranscriptionsTranscriptionIdTitlePatch(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            }
          )
        return data
      },
    }
    return mutationOptions
  }

/**
 * Rename Speaker Everywhere
 */
export const renameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchMutation =
  (
    options?: Partial<
      Options<RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData>
    >
  ): UseMutationOptions<
    RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponse,
    RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchError,
    Options<RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData>
  > => {
    const mutationOptions: UseMutationOptions<
      RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchResponse,
      RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchError,
      Options<RenameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatchData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await renameSpeakerEverywhereTranscriptionsTranscriptionIdSpeakersPatch(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            }
          )
        return data
      },
    }
    return mutationOptions
  }

/**
 * Update Dialogue Entry Speaker
 */
export const updateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchMutation =
  (
    options?: Partial<
      Options<UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData>
    >
  ): UseMutationOptions<
    UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponse,
    UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchError,
    Options<UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData>
  > => {
    const mutationOptions: UseMutationOptions<
      UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchResponse,
      UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchError,
      Options<UpdateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatchData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await updateDialogueEntrySpeakerTranscriptionsTranscriptionIdDialogueEntriesEntryIndexSpeakerPatch(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            }
          )
        return data
      },
    }
    return mutationOptions
  }

/**
 * Update Dialogue Entry Text
 */
export const updateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchMutation =
  (
    options?: Partial<
      Options<UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData>
    >
  ): UseMutationOptions<
    UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponse,
    UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchError,
    Options<UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData>
  > => {
    const mutationOptions: UseMutationOptions<
      UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchResponse,
      UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchError,
      Options<UpdateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatchData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await updateDialogueEntryTextTranscriptionsTranscriptionIdDialogueEntriesEntryIndexTextPatch(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            }
          )
        return data
      },
    }
    return mutationOptions
  }

export const getUserUsersMeGetQueryKey = (
  options?: Options<GetUserUsersMeGetData>
) => createQueryKey('getUserUsersMeGet', options)

/**
 * Get User
 */
export const getUserUsersMeGetOptions = (
  options?: Options<GetUserUsersMeGetData>
) =>
  queryOptions<
    GetUserUsersMeGetResponse,
    GetUserUsersMeGetError,
    GetUserUsersMeGetResponse,
    ReturnType<typeof getUserUsersMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserUsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserUsersMeGetQueryKey(options),
  })

/**
 * Accept Terms Of Use
 */
export const acceptTermsOfUseUsersTermsOfUsePostMutation = (
  options?: Partial<Options<AcceptTermsOfUseUsersTermsOfUsePostData>>
): UseMutationOptions<
  AcceptTermsOfUseUsersTermsOfUsePostResponse,
  AcceptTermsOfUseUsersTermsOfUsePostError,
  Options<AcceptTermsOfUseUsersTermsOfUsePostData>
> => {
  const mutationOptions: UseMutationOptions<
    AcceptTermsOfUseUsersTermsOfUsePostResponse,
    AcceptTermsOfUseUsersTermsOfUsePostError,
    Options<AcceptTermsOfUseUsersTermsOfUsePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await acceptTermsOfUseUsersTermsOfUsePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update Data Retention
 *
 * Update the data retention period for the current user.
 *
 * Args:
 * data: Request body containing data_retention_days
 * current_user: The current authenticated user
 */
export const updateDataRetentionUsersDataRetentionPatchMutation = (
  options?: Partial<Options<UpdateDataRetentionUsersDataRetentionPatchData>>
): UseMutationOptions<
  UpdateDataRetentionUsersDataRetentionPatchResponse,
  UpdateDataRetentionUsersDataRetentionPatchError,
  Options<UpdateDataRetentionUsersDataRetentionPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateDataRetentionUsersDataRetentionPatchResponse,
    UpdateDataRetentionUsersDataRetentionPatchError,
    Options<UpdateDataRetentionUsersDataRetentionPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateDataRetentionUsersDataRetentionPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listUsersUsersGetQueryKey = (
  options?: Options<ListUsersUsersGetData>
) => createQueryKey('listUsersUsersGet', options)

/**
 * List Users
 */
export const listUsersUsersGetOptions = (
  options?: Options<ListUsersUsersGetData>
) =>
  queryOptions<
    ListUsersUsersGetResponse,
    ListUsersUsersGetError,
    ListUsersUsersGetResponse,
    ReturnType<typeof listUsersUsersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsersUsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listUsersUsersGetQueryKey(options),
  })

export const listUsersUsersGetInfiniteQueryKey = (
  options?: Options<ListUsersUsersGetData>
): QueryKey<Options<ListUsersUsersGetData>> =>
  createQueryKey('listUsersUsersGet', options, true)

/**
 * List Users
 */
export const listUsersUsersGetInfiniteOptions = (
  options?: Options<ListUsersUsersGetData>
) =>
  infiniteQueryOptions<
    ListUsersUsersGetResponse,
    ListUsersUsersGetError,
    InfiniteData<ListUsersUsersGetResponse>,
    QueryKey<Options<ListUsersUsersGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListUsersUsersGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUsersUsersGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listUsersUsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listUsersUsersGetInfiniteQueryKey(options),
    }
  )

/**
 * Create User
 */
export const createUserUsersPostMutation = (
  options?: Partial<Options<CreateUserUsersPostData>>
): UseMutationOptions<
  CreateUserUsersPostResponse,
  CreateUserUsersPostError,
  Options<CreateUserUsersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserUsersPostResponse,
    CreateUserUsersPostError,
    Options<CreateUserUsersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUserUsersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete User
 */
export const deleteUserUsersUserIdDeleteMutation = (
  options?: Partial<Options<DeleteUserUsersUserIdDeleteData>>
): UseMutationOptions<
  DeleteUserUsersUserIdDeleteResponse,
  DeleteUserUsersUserIdDeleteError,
  Options<DeleteUserUsersUserIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteUserUsersUserIdDeleteResponse,
    DeleteUserUsersUserIdDeleteError,
    Options<DeleteUserUsersUserIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUserUsersUserIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getTargetUserUsersUserIdGetQueryKey = (
  options: Options<GetTargetUserUsersUserIdGetData>
) => createQueryKey('getTargetUserUsersUserIdGet', options)

/**
 * Get Target User
 */
export const getTargetUserUsersUserIdGetOptions = (
  options: Options<GetTargetUserUsersUserIdGetData>
) =>
  queryOptions<
    GetTargetUserUsersUserIdGetResponse,
    GetTargetUserUsersUserIdGetError,
    GetTargetUserUsersUserIdGetResponse,
    ReturnType<typeof getTargetUserUsersUserIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTargetUserUsersUserIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTargetUserUsersUserIdGetQueryKey(options),
  })

/**
 * Update User Roles
 */
export const updateUserRolesUsersUserIdRolesPatchMutation = (
  options?: Partial<Options<UpdateUserRolesUsersUserIdRolesPatchData>>
): UseMutationOptions<
  UpdateUserRolesUsersUserIdRolesPatchResponse,
  UpdateUserRolesUsersUserIdRolesPatchError,
  Options<UpdateUserRolesUsersUserIdRolesPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserRolesUsersUserIdRolesPatchResponse,
    UpdateUserRolesUsersUserIdRolesPatchError,
    Options<UpdateUserRolesUsersUserIdRolesPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUserRolesUsersUserIdRolesPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const userExistsUsersUserExistsGetQueryKey = (
  options: Options<UserExistsUsersUserExistsGetData>
) => createQueryKey('userExistsUsersUserExistsGet', options)

/**
 * User Exists
 */
export const userExistsUsersUserExistsGetOptions = (
  options: Options<UserExistsUsersUserExistsGetData>
) =>
  queryOptions<
    UserExistsUsersUserExistsGetResponse,
    UserExistsUsersUserExistsGetError,
    UserExistsUsersUserExistsGetResponse,
    ReturnType<typeof userExistsUsersUserExistsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userExistsUsersUserExistsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: userExistsUsersUserExistsGetQueryKey(options),
  })

export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey =
  (
    options: Options<ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData>
  ) =>
    createQueryKey(
      'listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet',
      options
    )

/**
 * List Minutes For Transcription
 */
export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetOptions =
  (
    options: Options<ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData>
  ) =>
    queryOptions<
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse,
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetError,
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse,
      ReturnType<
        typeof listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey(
          options
        ),
    })

/**
 * Create Minute
 */
export const createMinuteTranscriptionTranscriptionIdMinutesPostMutation = (
  options?: Partial<
    Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
  >
): UseMutationOptions<
  unknown,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
  Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
    Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await createMinuteTranscriptionTranscriptionIdMinutesPost({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getMinuteMinutesMinutesIdGetQueryKey = (
  options: Options<GetMinuteMinutesMinutesIdGetData>
) => createQueryKey('getMinuteMinutesMinutesIdGet', options)

/**
 * Get Minute
 */
export const getMinuteMinutesMinutesIdGetOptions = (
  options: Options<GetMinuteMinutesMinutesIdGetData>
) =>
  queryOptions<
    GetMinuteMinutesMinutesIdGetResponse,
    GetMinuteMinutesMinutesIdGetError,
    GetMinuteMinutesMinutesIdGetResponse,
    ReturnType<typeof getMinuteMinutesMinutesIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMinuteMinutesMinutesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMinuteMinutesMinutesIdGetQueryKey(options),
  })

export const listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey = (
  options: Options<ListMinuteVersionsMinutesMinuteIdVersionsGetData>
) => createQueryKey('listMinuteVersionsMinutesMinuteIdVersionsGet', options)

/**
 * List Minute Versions
 */
export const listMinuteVersionsMinutesMinuteIdVersionsGetOptions = (
  options: Options<ListMinuteVersionsMinutesMinuteIdVersionsGetData>
) =>
  queryOptions<
    ListMinuteVersionsMinutesMinuteIdVersionsGetResponse,
    ListMinuteVersionsMinutesMinuteIdVersionsGetError,
    ListMinuteVersionsMinutesMinuteIdVersionsGetResponse,
    ReturnType<typeof listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMinuteVersionsMinutesMinuteIdVersionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey(options),
  })

/**
 * Create Minute Version
 */
export const createMinuteVersionMinutesMinuteIdVersionsPostMutation = (
  options?: Partial<Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>>
): UseMutationOptions<
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
  CreateMinuteVersionMinutesMinuteIdVersionsPostError,
  Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
    CreateMinuteVersionMinutesMinuteIdVersionsPostError,
    Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMinuteVersionMinutesMinuteIdVersionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Minute Version
 */
export const deleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteMutation = (
  options?: Partial<
    Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
  >
): UseMutationOptions<
  unknown,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
  Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
    Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey = (
  options: Options<GetMinuteVersionMinuteVersionsMinuteVersionIdGetData>
) => createQueryKey('getMinuteVersionMinuteVersionsMinuteVersionIdGet', options)

/**
 * Get Minute Version
 */
export const getMinuteVersionMinuteVersionsMinuteVersionIdGetOptions = (
  options: Options<GetMinuteVersionMinuteVersionsMinuteVersionIdGetData>
) =>
  queryOptions<
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse,
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetError,
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse,
    ReturnType<typeof getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMinuteVersionMinuteVersionsMinuteVersionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey(options),
  })

export const getTemplatesTemplatesGetQueryKey = (
  options?: Options<GetTemplatesTemplatesGetData>
) => createQueryKey('getTemplatesTemplatesGet', options)

/**
 * Get Templates
 *
 * Get metadata for all templates.
 */
export const getTemplatesTemplatesGetOptions = (
  options?: Options<GetTemplatesTemplatesGetData>
) =>
  queryOptions<
    GetTemplatesTemplatesGetResponse,
    GetTemplatesTemplatesGetError,
    GetTemplatesTemplatesGetResponse,
    ReturnType<typeof getTemplatesTemplatesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTemplatesTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTemplatesTemplatesGetQueryKey(options),
  })

export const getUserTemplatesUserTemplatesGetQueryKey = (
  options?: Options<GetUserTemplatesUserTemplatesGetData>
) => createQueryKey('getUserTemplatesUserTemplatesGet', options)

/**
 * Get User Templates
 */
export const getUserTemplatesUserTemplatesGetOptions = (
  options?: Options<GetUserTemplatesUserTemplatesGetData>
) =>
  queryOptions<
    GetUserTemplatesUserTemplatesGetResponse,
    GetUserTemplatesUserTemplatesGetError,
    GetUserTemplatesUserTemplatesGetResponse,
    ReturnType<typeof getUserTemplatesUserTemplatesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserTemplatesUserTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserTemplatesUserTemplatesGetQueryKey(options),
  })

/**
 * Create User Template
 */
export const createUserTemplateUserTemplatesPostMutation = (
  options?: Partial<Options<CreateUserTemplateUserTemplatesPostData>>
): UseMutationOptions<
  unknown,
  CreateUserTemplateUserTemplatesPostError,
  Options<CreateUserTemplateUserTemplatesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateUserTemplateUserTemplatesPostError,
    Options<CreateUserTemplateUserTemplatesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUserTemplateUserTemplatesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete User Template
 */
export const deleteUserTemplateUserTemplatesTemplateIdDeleteMutation = (
  options?: Partial<
    Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
  >
): UseMutationOptions<
  unknown,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
  Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
    Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUserTemplateUserTemplatesTemplateIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getUserTemplateUserTemplatesTemplateIdGetQueryKey = (
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData>
) => createQueryKey('getUserTemplateUserTemplatesTemplateIdGet', options)

/**
 * Get User Template
 */
export const getUserTemplateUserTemplatesTemplateIdGetOptions = (
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData>
) =>
  queryOptions<
    GetUserTemplateUserTemplatesTemplateIdGetResponse,
    GetUserTemplateUserTemplatesTemplateIdGetError,
    GetUserTemplateUserTemplatesTemplateIdGetResponse,
    ReturnType<typeof getUserTemplateUserTemplatesTemplateIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserTemplateUserTemplatesTemplateIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserTemplateUserTemplatesTemplateIdGetQueryKey(options),
  })

/**
 * Edit User Template
 */
export const editUserTemplateUserTemplatesTemplateIdPatchMutation = (
  options?: Partial<Options<EditUserTemplateUserTemplatesTemplateIdPatchData>>
): UseMutationOptions<
  unknown,
  EditUserTemplateUserTemplatesTemplateIdPatchError,
  Options<EditUserTemplateUserTemplatesTemplateIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    EditUserTemplateUserTemplatesTemplateIdPatchError,
    Options<EditUserTemplateUserTemplatesTemplateIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await editUserTemplateUserTemplatesTemplateIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Duplicate User Template
 */
export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePostMutation =
  (
    options?: Partial<
      Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
    >
  ): UseMutationOptions<
    unknown,
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
    Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
      Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          })
        return data
      },
    }
    return mutationOptions
  }

/**
 * Delete Chats
 */
export const deleteChatsTranscriptionsTranscriptionIdChatDeleteMutation = (
  options?: Partial<
    Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
  >
): UseMutationOptions<
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
  Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
    Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteChatsTranscriptionsTranscriptionIdChatDelete(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        }
      )
      return data
    },
  }
  return mutationOptions
}

export const listChatTranscriptionsTranscriptionIdChatGetQueryKey = (
  options: Options<ListChatTranscriptionsTranscriptionIdChatGetData>
) => createQueryKey('listChatTranscriptionsTranscriptionIdChatGet', options)

/**
 * List Chat
 */
export const listChatTranscriptionsTranscriptionIdChatGetOptions = (
  options: Options<ListChatTranscriptionsTranscriptionIdChatGetData>
) =>
  queryOptions<
    ListChatTranscriptionsTranscriptionIdChatGetResponse,
    ListChatTranscriptionsTranscriptionIdChatGetError,
    ListChatTranscriptionsTranscriptionIdChatGetResponse,
    ReturnType<typeof listChatTranscriptionsTranscriptionIdChatGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatTranscriptionsTranscriptionIdChatGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatTranscriptionsTranscriptionIdChatGetQueryKey(options),
  })

/**
 * Create Chat
 */
export const createChatTranscriptionsTranscriptionIdChatPostMutation = (
  options?: Partial<
    Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
  >
): UseMutationOptions<
  CreateChatTranscriptionsTranscriptionIdChatPostResponse,
  CreateChatTranscriptionsTranscriptionIdChatPostError,
  Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateChatTranscriptionsTranscriptionIdChatPostResponse,
    CreateChatTranscriptionsTranscriptionIdChatPostError,
    Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createChatTranscriptionsTranscriptionIdChatPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Chat
 *
 * Delete a specific transcription by ID.
 */
export const deleteChatTranscriptionsTranscriptionIdChatChatIdDeleteMutation = (
  options?: Partial<
    Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
  >
): UseMutationOptions<
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
  Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
    Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteChatTranscriptionsTranscriptionIdChatChatIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey = (
  options: Options<GetChatTranscriptionsTranscriptionIdChatChatIdGetData>
) =>
  createQueryKey('getChatTranscriptionsTranscriptionIdChatChatIdGet', options)

/**
 * Get Chat
 */
export const getChatTranscriptionsTranscriptionIdChatChatIdGetOptions = (
  options: Options<GetChatTranscriptionsTranscriptionIdChatChatIdGetData>
) =>
  queryOptions<
    GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse,
    GetChatTranscriptionsTranscriptionIdChatChatIdGetError,
    GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse,
    ReturnType<typeof getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChatTranscriptionsTranscriptionIdChatChatIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey:
      getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey(options),
  })

export const listOrganisationsOrganisationsGetQueryKey = (
  options?: Options<ListOrganisationsOrganisationsGetData>
) => createQueryKey('listOrganisationsOrganisationsGet', options)

/**
 * List Organisations
 *
 * List all organisations. Only accessible to system admins..
 */
export const listOrganisationsOrganisationsGetOptions = (
  options?: Options<ListOrganisationsOrganisationsGetData>
) =>
  queryOptions<
    ListOrganisationsOrganisationsGetResponse,
    ListOrganisationsOrganisationsGetError,
    ListOrganisationsOrganisationsGetResponse,
    ReturnType<typeof listOrganisationsOrganisationsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listOrganisationsOrganisationsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listOrganisationsOrganisationsGetQueryKey(options),
  })

/**
 * Create Organisation
 *
 * Create a new organisation. Only accessible to system admins.
 */
export const createOrganisationOrganisationsPostMutation = (
  options?: Partial<Options<CreateOrganisationOrganisationsPostData>>
): UseMutationOptions<
  CreateOrganisationOrganisationsPostResponse,
  CreateOrganisationOrganisationsPostError,
  Options<CreateOrganisationOrganisationsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateOrganisationOrganisationsPostResponse,
    CreateOrganisationOrganisationsPostError,
    Options<CreateOrganisationOrganisationsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createOrganisationOrganisationsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Organisation
 *
 * Delete an organisation. Only accessible to system admins.
 */
export const deleteOrganisationOrganisationsOrganisationIdDeleteMutation = (
  options?: Partial<
    Options<DeleteOrganisationOrganisationsOrganisationIdDeleteData>
  >
): UseMutationOptions<
  DeleteOrganisationOrganisationsOrganisationIdDeleteResponse,
  DeleteOrganisationOrganisationsOrganisationIdDeleteError,
  Options<DeleteOrganisationOrganisationsOrganisationIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteOrganisationOrganisationsOrganisationIdDeleteResponse,
    DeleteOrganisationOrganisationsOrganisationIdDeleteError,
    Options<DeleteOrganisationOrganisationsOrganisationIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteOrganisationOrganisationsOrganisationIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getOrganisationOrganisationsOrganisationIdGetQueryKey = (
  options: Options<GetOrganisationOrganisationsOrganisationIdGetData>
) => createQueryKey('getOrganisationOrganisationsOrganisationIdGet', options)

/**
 * Get Organisation
 *
 * Get organisation. Only accessible to organisation admins.
 */
export const getOrganisationOrganisationsOrganisationIdGetOptions = (
  options: Options<GetOrganisationOrganisationsOrganisationIdGetData>
) =>
  queryOptions<
    GetOrganisationOrganisationsOrganisationIdGetResponse,
    GetOrganisationOrganisationsOrganisationIdGetError,
    GetOrganisationOrganisationsOrganisationIdGetResponse,
    ReturnType<typeof getOrganisationOrganisationsOrganisationIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOrganisationOrganisationsOrganisationIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getOrganisationOrganisationsOrganisationIdGetQueryKey(options),
  })

/**
 * Update Organisation
 *
 * Update an organisation's allowed email domains. Accessible to system admins or the organisation's own admin.
 */
export const updateOrganisationOrganisationsOrganisationIdPatchMutation = (
  options?: Partial<
    Options<UpdateOrganisationOrganisationsOrganisationIdPatchData>
  >
): UseMutationOptions<
  UpdateOrganisationOrganisationsOrganisationIdPatchResponse,
  UpdateOrganisationOrganisationsOrganisationIdPatchError,
  Options<UpdateOrganisationOrganisationsOrganisationIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateOrganisationOrganisationsOrganisationIdPatchResponse,
    UpdateOrganisationOrganisationsOrganisationIdPatchError,
    Options<UpdateOrganisationOrganisationsOrganisationIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateOrganisationOrganisationsOrganisationIdPatch(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        }
      )
      return data
    },
  }
  return mutationOptions
}

export const listOrganisationsUsersOrganisationsOrganisationIdUsersGetQueryKey =
  (
    options: Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
  ) =>
    createQueryKey(
      'listOrganisationsUsersOrganisationsOrganisationIdUsersGet',
      options
    )

/**
 * List Organisations Users
 */
export const listOrganisationsUsersOrganisationsOrganisationIdUsersGetOptions =
  (
    options: Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
  ) =>
    queryOptions<
      ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponse,
      ListOrganisationsUsersOrganisationsOrganisationIdUsersGetError,
      ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponse,
      ReturnType<
        typeof listOrganisationsUsersOrganisationsOrganisationIdUsersGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listOrganisationsUsersOrganisationsOrganisationIdUsersGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true,
          })
        return data
      },
      queryKey:
        listOrganisationsUsersOrganisationsOrganisationIdUsersGetQueryKey(
          options
        ),
    })

export const listOrganisationsUsersOrganisationsOrganisationIdUsersGetInfiniteQueryKey =
  (
    options: Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
  ): QueryKey<
    Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
  > =>
    createQueryKey(
      'listOrganisationsUsersOrganisationsOrganisationIdUsersGet',
      options,
      true
    )

/**
 * List Organisations Users
 */
export const listOrganisationsUsersOrganisationsOrganisationIdUsersGetInfiniteOptions =
  (
    options: Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
  ) =>
    infiniteQueryOptions<
      ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponse,
      ListOrganisationsUsersOrganisationsOrganisationIdUsersGetError,
      InfiniteData<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetResponse>,
      QueryKey<
        Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
      >,
      | number
      | Pick<
          QueryKey<
            Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
          >[0],
          'body' | 'headers' | 'path' | 'query'
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<ListOrganisationsUsersOrganisationsOrganisationIdUsersGetData>
            >[0],
            'body' | 'headers' | 'path' | 'query'
          > =
            typeof pageParam === 'object'
              ? pageParam
              : {
                  query: {
                    page: pageParam,
                  },
                }
          const params = createInfiniteParams(queryKey, page)
          const { data } =
            await listOrganisationsUsersOrganisationsOrganisationIdUsersGet({
              ...options,
              ...params,
              signal,
              throwOnError: true,
            })
          return data
        },
        queryKey:
          listOrganisationsUsersOrganisationsOrganisationIdUsersGetInfiniteQueryKey(
            options
          ),
      }
    )

export const signOutSignoutGetQueryKey = (
  options?: Options<SignOutSignoutGetData>
) => createQueryKey('signOutSignoutGet', options)

/**
 * Sign Out
 *
 * Sign out the user by clearing ALB auth cookies and redirecting to the IdP.
 */
export const signOutSignoutGetOptions = (
  options?: Options<SignOutSignoutGetData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof signOutSignoutGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await signOutSignoutGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: signOutSignoutGetQueryKey(options),
  })
